server:
  addr: "397841.vm.spacecore.network:443"
  sni: "397841.vm.spacecore.network"

auth:
  server_public_key: "e858568789b3522748dfba5542d367ac7e7d672b6d221bdef72c6cfd4480e623"
  client_private_key: "e09fed315c42f932f94cc3c53ab7fb839b1b5dc6eef59bd26998c9407894cb63"

proxy:
  mode: "socks5"
  socks5: "127.0.0.1:1080"
  dns: "1.1.1.1:53"

shaping:
  default_mode: "balanced"
  profile_path: "profiles/chrome_browsing.json"
  auto_mode: true

log:
  level: "info"
  file: "stdout"
