package auth

import (
	"crypto/subtle"
	"fmt"
)

// ServerAuth handles server-side authentication.
type ServerAuth interface {
	// VerifySessionID checks whether the ClientHello SessionID
	// was generated by a legitimate client.
	// random is ClientHello.Random, sessionID is the presented SessionID.
	// If valid, returns the shared secret for this client (needed for token verification).
	VerifySessionID(random, sessionID []byte) (sharedSecret [32]byte, ok bool)

	// VerifyToken checks the session token from an HTTP/2 request header.
	// sharedSecret is the value returned from a prior VerifySessionID call.
	// binding is the channel-binding value from the TLS connection.
	VerifyToken(sharedSecret [32]byte, binding []byte, token string) bool
}

// serverAuth implements ServerAuth with key pinning.
// It holds the server's private key and a list of precomputed
// shared secrets for each allowed client (key pinning model).
type serverAuth struct {
	clientSecrets [][32]byte
}

// NewServerAuth creates a ServerAuth from the server's private key
// and the list of allowed client public keys.
// It precomputes shared secrets for each client at construction time.
func NewServerAuth(serverPriv [32]byte, clientPubs [][32]byte) (ServerAuth, error) {
	secrets := make([][32]byte, len(clientPubs))
	for i, pub := range clientPubs {
		s, err := SharedSecret(serverPriv, pub)
		if err != nil {
			return nil, fmt.Errorf("auth.ServerAuth.New: client %d: %w", i, err)
		}
		secrets[i] = s
	}
	return &serverAuth{clientSecrets: secrets}, nil
}

// VerifySessionID tries each precomputed shared secret to find one
// that produces a matching SessionID. Returns the matching shared
// secret if found. Always iterates all secrets to avoid timing
// side-channels.
func (s *serverAuth) VerifySessionID(random, sessionID []byte) ([32]byte, bool) {
	var matched [32]byte
	found := 0
	for _, secret := range s.clientSecrets {
		expected := ComputeSessionID(secret, random)
		if subtle.ConstantTimeCompare(expected, sessionID) == 1 {
			matched = secret
			found = 1
		}
	}
	return matched, found == 1
}

// VerifyToken checks the session token using the shared secret
// and channel binding.
func (s *serverAuth) VerifyToken(sharedSecret [32]byte, binding []byte, token string) bool {
	return VerifySessionToken(sharedSecret, binding, token)
}
